# Generated by Django 2.2.7 on 2020-02-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='EmployeeAPI',
        ),
    ]
