# Generated by Django 2.2.7 on 2020-02-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API1', '0002_auto_20200206_2257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeAPI',
            new_name='Employee',
        ),
    ]
